### ISSUE TITLE
Can't install addon to Blender

### ISSUE THREAD

**Issue by BlumpkinKing87** [stuffmatic/fSpy-Blender#12]
I've tried in Blender 2.8 RC, 2.8 Beta and 2.79 to install from file and the addon is still nowhere to be found in any version. I only get this message in the log.
![image](https://user-images.githubusercontent.com/50567298/61177274-bf058c00-a596-11e9-8963-caf90d79024f.png)

**Comment by designjohnsen** [comment]
I had the same issue when installing from within blender, but manually installing it worked for me.

1. Unzip fSpy-Blender-1.0.2
2. Drag the folder named **fspy_blender** into the blender addon folder "2.80\scripts\addons"
3. You should see it pop up in the addon tab inside Blender

Hope this works for you too.

**Comment by BlumpkinKing87** [comment]
You rock! I should have just tried that in the first place but by then I had already moved on with the project I wanted to put fSpy to use with lol. I'll have it for next time though!
