### ISSUE TITLE
Unable to activate fspy

### ISSUE THREAD

**Issue by Gligatron** [stuffmatic/fSpy-Blender#13]
After installing the add-on (both manually and from within Blender) I am unable to activate it. This is the error I get from Blender 2.79:

![01](https://user-images.githubusercontent.com/53529656/62221569-22bef000-b3b2-11e9-9629-e93d95d330aa.jpg)

I tried restarting Blender and the computer, reinstalling the add-on but nothing changes.

**Comment by SavMartin** [comment]
This version its for Blender 2.80

**Comment by Gligatron** [comment]
That explains a lot :D Thanks. 

I have in the meantime installed version 1.0.2 and it's working perfectly.
