### ISSUE TITLE
multiple cameras

### ISSUE THREAD

**Issue by bladesman61** [stuffmatic/fSpy-Blender#14]
I need to create multiple cameras over the same geometry (multiple shots of the same scene with a digital floor). Could do that easily with blam. Can I do that with fspy?

**Comment by stuffmatic** [comment]
fSpy is probably your best bet, since the fSpy importer creates a camera with the same name as the imported fSpy file, so you should be able to just

* create one fSpy file per camera angle
* make sure no two files have the same name
* import the files them one at a time

**Comment by franMarz** [comment]
As of my experiences I can say that if the images have the same aspect ratio, e.g. have been taken with the same camera, you shouldn't face any issue.
