### ISSUE TITLE
Can't set custom sensor size

### ISSUE THREAD

**Issue by ecations** [stuffmatic/fSpy-Blender#19]
I'm trying to give fSpy the exact dimensions of the sensor of my phone's camera. I'm expecting "custom camera" drop down option to allow me to do that, but any value I input into the fields gets overridden.

**Comment by stuffmatic** [comment]
Did you hit return after entering the value? This has surprised a few other users.

**Comment by Copperplate** [comment]
Thanks! That's exactly what the issue was. Although most users would never suspect to do this, so perhaps a tooltip such as "Type value then press Enter" might prove helpful. Fantastic software, really produces excellent results. Thank you so much for creating this!

**Comment by walles** [comment]
@stuffmatic if I made a PR to fix this, would you consider making a new release with the fix in it?
