### ISSUE TITLE
import

### ISSUE THREAD

**Issue by ZawszeNigdy** [stuffmatic/fSpy-Blender#2]
Project exported from fSpy. fSpy save project without extension. In both cases (trying to import file without extension and file with extension wrote by myself) i have same error. Blender 2.8 and checked in 2.79 too. fSpy 1.0.1.

![bez nazwy](https://user-images.githubusercontent.com/28146372/49345121-c075ea00-f680-11e8-8698-2c0f56569875.png)

**Comment by stuffmatic** [comment]
It would be interesting to have a look at the file(s) you're trying to import. Could you provide a download link?

**Comment by stuffmatic** [comment]
This seems to happen when trying to import a JSON file exported from fSpy. The importer only supports fSpy project files (created using "save" rather then "export"). Will add a better check for this in the next version
