### ISSUE TITLE
Cant Import fspy file in Blender 2.79

### ISSUE THREAD

**Issue by Vickievik** [stuffmatic/fSpy-Blender#20]
Installed addon version 1.0.3, Trying to import .fspy file in BLender 2.79, but it throws an error.

![fspyerror](https://user-images.githubusercontent.com/48504909/65214252-f298f100-dac6-11e9-852b-1f10e75f4833.jpg)

Kindly Help. I love this Application, its awesome, but doesnt works for me....
THanks for Developing it and sharing with us.

Vickievik

**Comment by stuffmatic** [comment]
Please use v 1.0.2 of the add on for Blender 2.79 

https://github.com/stuffmatic/fSpy-Blender#support-for-blender-versions-older-than-280

**Comment by Vickievik** [comment]
Hi,, Thanks for this help myfriend. Though next I faced the issue in installing the plugin, but instead copy pasting the addon in addons folder solved the problem....

Thanks and Regards StuffMatic
Vickievik
