### ISSUE TITLE
Fspy won't install in Blender Mac

### ISSUE THREAD

**Issue by matwolfe** [stuffmatic/fSpy-Blender#22]
After INSTALL ADDON FROM FILE...I tried installing from the Zip file 1.0.3.  It installs, then when you click Import/Export fSpy check box, I get an error message that says.....Installing the dmg file does not work, so the only option is to install the zip file over and over and get the same error message.  Any way to help out this situation?  Many Thanks!  Matwolfe@hotmail.com
![Screen Shot 2019-10-31 at 5 43 24 PM](https://user-images.githubusercontent.com/57237842/67988675-193e6180-fc07-11e9-885e-2a5594383124.png)

**Comment by stuffmatic** [comment]
Looks like you're using a pre 2.80 version of Blender? If so, please use version 1.0.2 of the addon

https://github.com/stuffmatic/fSpy-Blender#support-for-blender-versions-older-than-280

**Comment by matwolfe** [comment]
You are most correct!  It loaded perfectly.  Thank you very much, now to play with an image!  best to you, matt
