### ISSUE TITLE
MINOR - About menu

### ISSUE THREAD

**Issue by mvittiglio** [stuffmatic/fSpy-Blender#4]
A very minor gripe but thought I would share: it would be nice to have an "about" dialog showing the current version.

Gold plating: link to release notes on GitHub and a "check for updates" option.

Nice work btw! I tried to dip my toe into Electron as well but the project fell through. 👍

**Comment by stuffmatic** [comment]
Fixed in https://github.com/stuffmatic/fSpy/commit/da632c2c7499b751d1c2480f7998b1d5de0943a5
