### ISSUE TITLE
Cant install on blender 2.9

### ISSUE THREAD

**Issue by NiceErJeg** [stuffmatic/fSpy-Blender#41]
when installing on blender 2.9 it wont show the addon when pressing install and selecting the zip folder

**Comment by stuffmatic** [comment]
Did you download fSpy-Blender-1.0.3.zip from the [releases section](https://github.com/stuffmatic/fSpy-Blender/releases)?

**Comment by NiceErJeg** [comment]
Thank you, that did it, idk what went wrong though

**Comment by stuffmatic** [comment]
Maybe you pressed the download button for the repository?
