### ISSUE TITLE
Cannot import fspy file to blender

### ISSUE THREAD

**Issue by danman24** [stuffmatic/fSpy-Blender#49]
I have tried several times to import my file into blender and I keep getting the same error. I have also tried to redownload Fspy and the addon and every time I import the file I still get this message. I am also including the file I am trying to import incase that helps at all. I am using blender version 2.93 and version 1.0.3 of fspy and same version for addon.
[kitchen.zip](https://github.com/stuffmatic/fSpy-Blender/files/6980894/kitchen.zip)
![Screenshot 2021-08-13 041246](https://user-images.githubusercontent.com/88878856/129326089-b2f08281-bf3a-4f5b-b6ec-057eaf26ffdf.jpg)

**Comment by stuffmatic** [comment]
@danman24 Did you get this to work?
