### ISSUE TITLE
Does not work in latest update? 

### ISSUE THREAD

**Issue by ErnstssonJohan** [stuffmatic/fSpy-Blender#6]
When I try to import fspy file i now get this error message: 
![image](https://user-images.githubusercontent.com/10749624/52122281-b9d50600-2622-11e9-886e-e5348473f7e0.png)

**Comment by raineEM** [comment]
try switching a vanishing point axis to negative, that worked for me.

**Comment by jonbragado** [comment]
I get the same exact error. Tried swapping the axis to a negative axis but still getting the same issue. 
Some help would be much appreciated.

**Comment by jonbragado** [comment]
Works with the latest Blender build. All good.

**Comment by MichelPWeber** [comment]
I know this is closed, but I'll still replay and state I'm getting the same error.
Not sure how changing the polarity of the axis can resolve a file not found error.

**Comment by MichelPWeber** [comment]
I ran Blender as Administrator, on Windows, and it took care of the problem.  It was looking in the temp folder for the file inside a Blender... folder which didn't exist. I suspect it was not able to create the folder when running Blender as non-admin, so tried again as Admin and it worked.

**Comment by Woaaaaaaaaaaah** [comment]
Oh my god, thanks, my dude :D! Wth, These errors hurt your answer with the admin thing worked
