### ISSUE TITLE
Switching From Camera View to Perspective View Rotates Model 180°?

### ISSUE THREAD

**Issue by gefitch** [stuffmatic/fSpy-Blender#7]
Dear Support,

I really like your Fspy App. Very helpful. Great work.

I'm currently using Fspy 1.0.2 in Blender 2.8 Beta as of 02/05/2019 install on Windows 10. 

I am having an issue when I switch from Camera view to Perspective view. It rotates the model 180° in the viewport? If I switch back to Camera view all is well again, Of course, if I manually rotate the model while in perspective view it is then upside down in Fspy Camera view.

I did all the same things in Blender 2.79 and there was no rotation applied there. So, appears on  my end to just be 2.8.

I'm hoping there's a simple setting I can change?

Thanks,

Gary

**Comment by stuffmatic** [comment]
Could you perhaps provide the .fspy and .blend files?

**Comment by gefitch** [comment]
[Boxcar Inside.zip](https://github.com/stuffmatic/fSpy-Blender/files/2845561/Boxcar.Inside.zip)

**Comment by stuffmatic** [comment]
Looking at the .fSpy file, the z axis is pointing down, which seems to be consistent with the camera in the .blend file. Switching the axis of vanishing point 2 from z to -z and re-importing the project should fix the problem as far as I can tell.

**Comment by gefitch** [comment]
That fixed it!  Thank you so much for the quick turnaround on this!
